### ISSUE TITLE
Building the app with this template fails 

### ISSUE THREAD

**Issue by adriatic** [jc-verse/docusaurus-template#1]
The errors are described below:

```
Starting the development server...
Docusaurus website is running at "http://localhost:3000/".
Error: @docusaurus/core tried to access @docusaurus/mdx-loader, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @docusaurus/mdx-loader
Required by: @docusaurus/core@virtual:4e678a97f9ee361b1f49d0cca7f9280632cbc56fe318d4e46af631b0be9fc35e6d1e0bb6ab5bd037dc332f15b1a8a0f9cdb89757e679bdd23b9a217ddacfc954#npm:2.0.0-beta.6 (via /Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/server/)

Require stack:
- /Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/server/index.js
- /Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/commands/build.js
- /Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/index.js
- /Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/bin/docusaurus.js
    at Function.require$$0.Module._resolveFilename (/Users/nik/dev/work/redwood/docs/personal-page/.pnp.cjs:24336:13)
    at Function.Module._resolveFilename (/Users/nik/dev/work/redwood/docs/personal-page/.yarn/cache/module-alias-npm-2.2.2-576bd37c03-4b5543f834.zip/node_modules/module-alias/index.js:49:29)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.configureWebpack (/Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/server/index.js:164:53)
    at Object.applyConfigureWebpack (/Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/webpack/utils.js:148:43)
    at /Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/commands/start.js:122:30
    at Array.forEach (<anonymous>)
    at start (/Users/nik/dev/work/redwood/docs/personal-page/.yarn/__virtual__/@docusaurus-core-virtual-dbe8a9fe7c/0/cache/@docusaurus-core-npm-2.0.0-beta.6-8177d2ee39-369e78e798.zip/node_modules/@docusaurus/core/lib/commands/start.js:115:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
nik$ 
```

The output of `yarn info` description of my environment is:

```
nik$ yarn info 
├─ @docusaurus/core@npm:2.0.0-beta.6
│  ├─ Instances: 1
│  ├─ Version: 2.0.0-beta.6
│  │
│  ├─ Exported Binaries
│  │  └─ docusaurus
│  │
│  └─ Dependencies
│     ├─ @babel/core@npm:^7.12.16 → npm:7.17.8
│     ├─ @babel/generator@npm:^7.12.15 → npm:7.17.7
│     ├─ @babel/plugin-syntax-dynamic-import@npm:^7.8.3 → npm:7.8.3
│     ├─ @babel/plugin-transform-runtime@npm:^7.12.15 → npm:7.17.0
│     ├─ @babel/preset-env@npm:^7.12.16 → npm:7.16.11
│     ├─ @babel/preset-react@npm:^7.12.13 → npm:7.16.7
│     ├─ @babel/preset-typescript@npm:^7.12.16 → npm:7.16.7
│     ├─ @babel/runtime-corejs3@npm:^7.12.13 → npm:7.17.8
│     ├─ @babel/runtime@npm:^7.12.5 → npm:7.17.8
│     ├─ @babel/traverse@npm:^7.12.13 → npm:7.17.3
│     ├─ @docusaurus/cssnano-preset@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/react-loadable@npm:5.5.0 → npm:5.5.0
│     ├─ @docusaurus/types@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/utils-common@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/utils-validation@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/utils@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @slorber/static-site-generator-webpack-plugin@npm:^4.0.0 → npm:4.0.4
│     ├─ @svgr/webpack@npm:^5.5.0 → npm:5.5.0
│     ├─ autoprefixer@npm:^10.2.5 → npm:10.4.4
│     ├─ babel-loader@npm:^8.2.2 → npm:8.2.4
│     ├─ babel-plugin-dynamic-import-node@npm:2.3.0 → npm:2.3.0
│     ├─ boxen@npm:^5.0.1 → npm:5.1.2
│     ├─ chalk@npm:^4.1.1 → npm:4.1.2
│     ├─ chokidar@npm:^3.5.1 → npm:3.5.3
│     ├─ clean-css@npm:^5.1.5 → npm:5.3.0
│     ├─ commander@npm:^5.1.0 → npm:5.1.0
│     ├─ copy-webpack-plugin@npm:^9.0.0 → npm:9.1.0
│     ├─ core-js@npm:^3.9.1 → npm:3.21.1
│     ├─ css-loader@npm:^5.1.1 → npm:5.2.7
│     ├─ css-minimizer-webpack-plugin@npm:^3.0.1 → npm:3.4.1
│     ├─ cssnano@npm:^5.0.4 → npm:5.1.7
│     ├─ del@npm:^6.0.0 → npm:6.0.0
│     ├─ detect-port@npm:^1.3.0 → npm:1.3.0
│     ├─ escape-html@npm:^1.0.3 → npm:1.0.3
│     ├─ eta@npm:^1.12.1 → npm:1.12.3
│     ├─ express@npm:^4.17.1 → npm:4.17.3
│     ├─ file-loader@npm:^6.2.0 → npm:6.2.0
│     ├─ fs-extra@npm:^10.0.0 → npm:10.0.1
│     ├─ github-slugger@npm:^1.3.0 → npm:1.4.0
│     ├─ globby@npm:^11.0.2 → npm:11.1.0
│     ├─ html-minifier-terser@npm:^5.1.1 → npm:5.1.1
│     ├─ html-tags@npm:^3.1.0 → npm:3.1.0
│     ├─ html-webpack-plugin@npm:^5.3.2 → npm:5.5.0
│     ├─ import-fresh@npm:^3.3.0 → npm:3.3.0
│     ├─ is-root@npm:^2.1.0 → npm:2.1.0
│     ├─ leven@npm:^3.1.0 → npm:3.1.0
│     ├─ lodash@npm:^4.17.20 → npm:4.17.21
│     ├─ mini-css-extract-plugin@npm:^1.6.0 → npm:1.6.2
│     ├─ module-alias@npm:^2.2.2 → npm:2.2.2
│     ├─ nprogress@npm:^0.2.0 → npm:0.2.0
│     ├─ postcss-loader@npm:^5.3.0 → npm:5.3.0
│     ├─ postcss@npm:^8.2.15 → npm:8.4.12
│     ├─ prompts@npm:^2.4.1 → npm:2.4.2
│     ├─ react-dev-utils@npm:^11.0.1 → npm:11.0.4
│     ├─ react-error-overlay@npm:^6.0.9 → npm:6.0.10
│     ├─ react-helmet@npm:^6.1.0 → npm:6.1.0
│     ├─ react-loadable-ssr-addon-v5-slorber@npm:^1.0.1 → npm:1.0.1
│     ├─ react-loadable@npm:^5.5.0 → npm:5.5.0
│     ├─ react-router-config@npm:^5.1.1 → npm:5.1.1
│     ├─ react-router-dom@npm:^5.2.0 → npm:5.3.0
│     ├─ react-router@npm:^5.2.0 → npm:5.2.1
│     ├─ remark-admonitions@npm:^1.2.1 → npm:1.2.1
│     ├─ resolve-pathname@npm:^3.0.0 → npm:3.0.0
│     ├─ rtl-detect@npm:^1.0.3 → npm:1.0.4
│     ├─ semver@npm:^7.3.4 → npm:7.3.5
│     ├─ serve-handler@npm:^6.1.3 → npm:6.1.3
│     ├─ shelljs@npm:^0.8.4 → npm:0.8.5
│     ├─ std-env@npm:^2.2.1 → npm:2.3.1
│     ├─ strip-ansi@npm:^6.0.0 → npm:6.0.1
│     ├─ terser-webpack-plugin@npm:^5.1.3 → npm:5.3.1
│     ├─ tslib@npm:^2.2.0 → npm:2.3.1
│     ├─ update-notifier@npm:^5.1.0 → npm:5.1.0
│     ├─ url-loader@npm:^4.1.1 → npm:4.1.1
│     ├─ wait-on@npm:^5.3.0 → npm:5.3.0
│     ├─ webpack-bundle-analyzer@npm:^4.4.2 → npm:4.5.0
│     ├─ webpack-dev-server@npm:^3.11.2 → npm:3.11.3
│     ├─ webpack-merge@npm:^5.8.0 → npm:5.8.0
│     ├─ webpack@npm:^5.40.0 → npm:5.71.0
│     └─ webpackbar@npm:^5.0.0-3 → npm:5.0.2
│
├─ @docusaurus/preset-classic@npm:2.0.0-beta.6
│  ├─ Instances: 1
│  ├─ Version: 2.0.0-beta.6
│  │
│  └─ Dependencies
│     ├─ @docusaurus/core@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/plugin-content-blog@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/plugin-content-docs@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/plugin-content-pages@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/plugin-debug@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/plugin-google-analytics@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/plugin-google-gtag@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/plugin-sitemap@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     ├─ @docusaurus/theme-classic@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│     └─ @docusaurus/theme-search-algolia@npm:2.0.0-beta.6 → npm:2.0.0-beta.6
│
├─ @mdx-js/react@npm:1.6.22
│  ├─ Instances: 1
│  └─ Version: 1.6.22
│
├─ @svgr/webpack@npm:5.5.0
│  ├─ Version: 5.5.0
│  │
│  └─ Dependencies
│     ├─ @babel/core@npm:^7.12.3 → npm:7.17.8
│     ├─ @svgr/core@npm:^5.5.0 → npm:5.5.0
│     ├─ @svgr/plugin-jsx@npm:^5.5.0 → npm:5.5.0
│     ├─ @svgr/plugin-svgo@npm:^5.5.0 → npm:5.5.0
│     ├─ loader-utils@npm:^2.0.0 → npm:2.0.2
│     ├─ @babel/plugin-transform-react-constant-elements@npm:^7.12.1 → npm:7.17.6 [0d3ac]
│     ├─ @babel/preset-env@npm:^7.12.1 → npm:7.16.11 [0d3ac]
│     └─ @babel/preset-react@npm:^7.12.5 → npm:7.16.7 [0d3ac]
│
├─ clsx@npm:1.1.1
│  └─ Version: 1.1.1
│
├─ file-loader@npm:6.2.0
│  ├─ Instances: 1
│  ├─ Version: 6.2.0
│  │
│  └─ Dependencies
│     ├─ loader-utils@npm:^2.0.0 → npm:2.0.2
│     └─ schema-utils@npm:^3.0.0 → npm:3.1.1
│
├─ personal-page@workspace:.
│  ├─ Version: 0.0.0
│  │
│  └─ Dependencies
│     ├─ @svgr/webpack@npm:^5.5.0 → npm:5.5.0
│     ├─ clsx@npm:^1.1.1 → npm:1.1.1
│     ├─ react@npm:^17.0.1 → npm:17.0.2
│     ├─ @docusaurus/core@npm:2.0.0-beta.6 → npm:2.0.0-beta.6 [4e678]
│     ├─ @docusaurus/preset-classic@npm:2.0.0-beta.6 → npm:2.0.0-beta.6 [4e678]
│     ├─ @mdx-js/react@npm:^1.6.21 → npm:1.6.22 [4e678]
│     ├─ file-loader@npm:^6.2.0 → npm:6.2.0 [4e678]
│     ├─ prism-react-renderer@npm:^1.2.1 → npm:1.3.1 [4e678]
│     ├─ react-dom@npm:^17.0.1 → npm:17.0.2 [4e678]
│     └─ url-loader@npm:^4.1.1 → npm:4.1.1 [4e678]
│
├─ prism-react-renderer@npm:1.3.1
│  ├─ Instances: 1
│  └─ Version: 1.3.1
│
├─ react-dom@npm:17.0.2
│  ├─ Instances: 1
│  ├─ Version: 17.0.2
│  │
│  └─ Dependencies
│     ├─ loose-envify@npm:^1.1.0 → npm:1.4.0
│     ├─ object-assign@npm:^4.1.1 → npm:4.1.1
│     └─ scheduler@npm:^0.20.2 → npm:0.20.2
│
├─ react@npm:17.0.2
│  ├─ Version: 17.0.2
│  │
│  └─ Dependencies
│     ├─ loose-envify@npm:^1.1.0 → npm:1.4.0
│     └─ object-assign@npm:^4.1.1 → npm:4.1.1
│
└─ url-loader@npm:4.1.1
   ├─ Instances: 1
   ├─ Version: 4.1.1
   │
   └─ Dependencies
      ├─ loader-utils@npm:^2.0.0 → npm:2.0.2
      ├─ mime-types@npm:^2.1.27 → npm:2.1.35
      └─ schema-utils@npm:^3.0.0 → npm:3.1.1
nik$ 
```

**Comment by Josh-Cena** [comment]
Hi, I think there's something fishy with your setup. First, this template uses the node-modules linker, not PnP; second, it's talking about `2.0.0-beta.6`, but this repo has already been bumped to `2.0.0-beta.16`. Could you make sure everything is the latest version?

**Comment by adriatic** [comment]
This is very weird - and I am not sure what `yarn info` does and where it gets all this information shown on my issue report. Let me do some research before responding.

**Comment by Josh-Cena** [comment]
Closing as it seems resolved...

**Comment by adriatic** [comment]
It is not resolved, because I did not follow your advice on how to to address this issue (your [note](https://github.com/jc-verse/docusaurus-template/issues/1#issuecomment-1086751978)). Keep it closed please - and I will reopen it if my verification of this problem fails

**Comment by Josh-Cena** [comment]
Ah, sure 👍 Reopen it as you wish
